// flow-typed signature: 37073f16e4af3296217e5829cb5830b3
// flow-typed version: <<STUB>>/firebase-functions-test_v^0.1.6/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase-functions-test'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase-functions-test' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebase-functions-test/lib/app' {
  declare module.exports: any;
}

declare module 'firebase-functions-test/lib/features' {
  declare module.exports: any;
}

declare module 'firebase-functions-test/lib/index' {
  declare module.exports: any;
}

declare module 'firebase-functions-test/lib/lifecycle' {
  declare module.exports: any;
}

declare module 'firebase-functions-test/lib/main' {
  declare module.exports: any;
}

declare module 'firebase-functions-test/lib/providers/analytics' {
  declare module.exports: any;
}

declare module 'firebase-functions-test/lib/providers/auth' {
  declare module.exports: any;
}

declare module 'firebase-functions-test/lib/providers/crashlytics' {
  declare module.exports: any;
}

declare module 'firebase-functions-test/lib/providers/database' {
  declare module.exports: any;
}

declare module 'firebase-functions-test/lib/providers/firestore' {
  declare module.exports: any;
}

declare module 'firebase-functions-test/lib/providers/pubsub' {
  declare module.exports: any;
}

declare module 'firebase-functions-test/lib/providers/storage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebase-functions-test/lib/app.js' {
  declare module.exports: $Exports<'firebase-functions-test/lib/app'>;
}
declare module 'firebase-functions-test/lib/features.js' {
  declare module.exports: $Exports<'firebase-functions-test/lib/features'>;
}
declare module 'firebase-functions-test/lib/index.js' {
  declare module.exports: $Exports<'firebase-functions-test/lib/index'>;
}
declare module 'firebase-functions-test/lib/lifecycle.js' {
  declare module.exports: $Exports<'firebase-functions-test/lib/lifecycle'>;
}
declare module 'firebase-functions-test/lib/main.js' {
  declare module.exports: $Exports<'firebase-functions-test/lib/main'>;
}
declare module 'firebase-functions-test/lib/providers/analytics.js' {
  declare module.exports: $Exports<'firebase-functions-test/lib/providers/analytics'>;
}
declare module 'firebase-functions-test/lib/providers/auth.js' {
  declare module.exports: $Exports<'firebase-functions-test/lib/providers/auth'>;
}
declare module 'firebase-functions-test/lib/providers/crashlytics.js' {
  declare module.exports: $Exports<'firebase-functions-test/lib/providers/crashlytics'>;
}
declare module 'firebase-functions-test/lib/providers/database.js' {
  declare module.exports: $Exports<'firebase-functions-test/lib/providers/database'>;
}
declare module 'firebase-functions-test/lib/providers/firestore.js' {
  declare module.exports: $Exports<'firebase-functions-test/lib/providers/firestore'>;
}
declare module 'firebase-functions-test/lib/providers/pubsub.js' {
  declare module.exports: $Exports<'firebase-functions-test/lib/providers/pubsub'>;
}
declare module 'firebase-functions-test/lib/providers/storage.js' {
  declare module.exports: $Exports<'firebase-functions-test/lib/providers/storage'>;
}
